import { cleanGoodToKnow } from "./good-to-know.js";
import { cleanHeroOptions } from "./hero-options.js";
import { resolvePageAccess } from "./page-visibility.js";
import { missingColumnName } from "./schema-compat.js";
import { assertServiceSupabase, requireAppUser, sendJson } from "./server.js";
import { audit } from "./audit.js";

/**
 * What an event looks like, on `PATCH /api/events?resource=appearance`.
 *
 * Reading is not here - the theme and the hero photograph travel with the
 * event in `?resource=data`, which every screen loads. Only the write needs
 * a route, and it needs edit access to the dashboard, because that is the
 * screen the appearance is mostly about.
 */

type ApiRequest = {
  method?: string;
  body?: unknown;
  query?: Record<string, unknown>;
  headers: { authorization?: string };
};

type ApiResponse = {
  setHeader?: (name: string, value: string) => void;
  status: (statusCode: number) => { json: (body: unknown) => void };
};

/** Mirrors src/lib/themes.ts. The server does not need to know what a preset
 *  looks like, only that it is one the app actually has - otherwise `theme`
 *  is a free-text column somebody can put a stylesheet in. */
const themeKeys = new Set(["teal", "marigold", "indigo", "rose", "forest"]);

/** The same rules migration 029's SQL slugify() applies: lower-cased,
 *  non-alphanumerics collapsed to single hyphens, trimmed. Kept in step with it
 *  deliberately - a slug typed here and one generated by the backfill must take
 *  the same shape or the two halves of this feature disagree. */
function slugify(value: unknown) {
  return String(value ?? "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function fail(message: string, statusCode: number) {
  const error = new Error(message);
  Object.assign(error, { statusCode });
  return error;
}

async function readBody(req: ApiRequest) {
  if (!req.body) return {} as Record<string, unknown>;
  if (typeof req.body === "string") return JSON.parse(req.body) as Record<string, unknown>;
  return req.body as Record<string, unknown>;
}

/**
 * The hero has to be an image this app stored. Accepting any URL would let an
 * admin point the dashboard at a third party, which quietly tells that third
 * party who opens a public event page and when.
 */
function cleanHeroUrl(value: unknown): string | null {
  const url = String(value ?? "").trim();
  if (!url) return null;
  if (!/^https:\/\/[^/]+\/storage\/v1\/object\/public\/uploads\/events\//.test(url)) {
    throw fail("A hero image has to be one uploaded through this app", 400);
  }
  return url.slice(0, 500);
}

export async function handleAppearance(req: ApiRequest, res: ApiResponse) {
  if (!["PATCH", "POST"].includes(String(req.method))) {
    sendJson(res, 405, { error: "Method not allowed" });
    return;
  }

  const supabase = assertServiceSupabase();
  const { appUser } = await requireAppUser(req);
  const body = await readBody(req);

  const eventId = String(body.eventId ?? "");
  if (!eventId) throw fail("eventId is required", 400);

  const access = await resolvePageAccess(eventId, appUser.id, "dashboard");
  if (!access.canEdit) throw fail("You do not have edit access to this event", 403);

  const updates: Record<string, unknown> = {};

  if (body.theme !== undefined) {
    const theme = String(body.theme ?? "");
    // An empty theme is "back to the app's own colours", not an error.
    if (theme && !themeKeys.has(theme)) throw fail("That is not a theme this app has", 400);
    updates.theme = theme || null;
  }

  if (body.heroImageUrl !== undefined) {
    updates.hero_image_url = cleanHeroUrl(body.heroImageUrl);
  }

  // How the hero is dressed: focal point, hidden title, subtitle. `null`
  // clears it back to what the hero has always done.
  if (body.heroOptions !== undefined) {
    updates.hero_options = body.heroOptions === null ? null : cleanHeroOptions(body.heroOptions);
  }

  // What residents should know that is not on the schedule. `null` clears it.
  if (body.goodToKnow !== undefined) {
    updates.good_to_know = body.goodToKnow === null ? null : cleanGoodToKnow(body.goodToKnow, true);
  }

  // The event half of its readable address. Slugified here with the same rules
  // migration 029's own slugify() uses, so a slug typed in Settings and one
  // generated by the backfill can never take different shapes.
  if (body.slug !== undefined) {
    const slug = slugify(body.slug);
    if (!slug) throw fail("An address needs at least one letter or number", 400);
    if (slug.length > 60) throw fail("That address is too long - keep it under 60 characters", 400);
    updates.slug = slug;
  }

  if (!Object.keys(updates).length) throw fail("Nothing to change", 400);

  // Select back only what was written. Asking for a column this write did not
  // touch means a database missing THAT column fails a save that had nothing
  // to do with it.
  const { data, error } = await supabase
    .from("events")
    .update(updates)
    .eq("id", eventId)
    .select(Object.keys(updates).join(","))
    .single();

  if (error) {
    // The unique index is (organization_id, slug): two events in one society
    // cannot share an address. Answer it as the usable sentence it is rather
    // than as a constraint name.
    if (error.code === "23505") {
      throw fail("Another event in this society already uses that address. Try a different one.", 409);
    }

    // Name the migration that column actually belongs to. This used to answer
    // "readable addresses need 029" for ANY missing column, so a database
    // without 027 told an admin who was uploading a hero image to run a
    // migration that had nothing to do with it.
    const column = missingColumnName(error);
    if (column === "slug") {
      throw fail(
        "Readable addresses need supabase/migrations/029_society_home.sql. Run it, then try again.",
        501,
      );
    }
    if (column === "good_to_know") {
      throw fail(
        "Writing 'Good to know' needs supabase/migrations/039_event_info_and_history.sql. Run it, then try again.",
        501,
      );
    }
    if (column === "hero_options") {
      throw fail(
        "Customising the hero needs supabase/migrations/035_hero_options.sql. Run it, then try again.",
        501,
      );
    }
    if (column && ["hero_image_url", "theme", "share_token"].includes(column)) {
      throw fail(
        "Changing how an event looks needs supabase/migrations/027_event_appearance.sql. Run it, then try again.",
        501,
      );
    }
    throw error;
  }

  const saved = data as unknown as Record<string, unknown>;

  audit(req, {
    action: "update",
    entityType: "event_appearance",
    entityId: eventId,
    eventId,
    actor: { id: appUser.id },
    after: updates,
    summary: "Changed this event's colour or hero photograph",
  });

  sendJson(res, 200, {
    theme: (saved.theme as string | null | undefined) ?? null,
    heroImageUrl: (saved.hero_image_url as string | null | undefined) ?? null,
    heroOptions: "hero_options" in saved ? cleanHeroOptions(saved.hero_options) : undefined,
    goodToKnow: "good_to_know" in saved ? cleanGoodToKnow(saved.good_to_know) : undefined,
    slug: (saved.slug as string | null | undefined) ?? null,
  });
}
