-- Who opens this event's pages, and for how long.
--
-- A committee maintains a schedule, writes a closing note and hands out a
-- share link with no way of knowing whether any of it is read. This is that
-- answer, surfaced as an admin-only panel in Settings.
--
-- It is a record of people's browsing, so the shape of it is a privacy
-- decision as much as a storage one. Three choices below are deliberate and
-- each would be easy to undo by accident.

create table if not exists public.event_visits (
  -- The visit's own id, generated by the client and held in sessionStorage,
  -- which is what makes the heartbeat an upsert on a primary key rather than
  -- a read-then-write with a race in the middle. A new tab is a new visit.
  id uuid primary key,
  event_id uuid not null references public.events(id) on delete cascade,

  -- A random value the visitor's browser generates once and keeps in
  -- localStorage. It groups a guest's repeat visits and identifies nobody.
  --
  -- ONE ROW PER VISIT, NOT PER PAGE VIEW. Time spent is
  -- last_seen_at - started_at, which needs no second table and no join. The
  -- path somebody took through the site is deliberately not recorded: a
  -- per-view log is five to ten times the rows and a far more intimate record
  -- of one person's behaviour than a committee needs in order to learn
  -- whether its pages are read. If that is ever wanted, it is a new decision,
  -- not a column to add here quietly.
  visitor_key text not null,

  -- Set only when the visitor was signed in. Null is a guest, and a guest
  -- stays a guest - there is nothing else to resolve them by.
  user_id uuid references public.app_users(id) on delete set null,

  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),

  -- The page they are on now, as a page key ("dashboard", "closing"). The
  -- server only records one it has confirmed this viewer may actually open.
  page_key text,
  page_views integer not null default 1,

  -- NO IP ADDRESS IS STORED HERE, IN ANY FORM - NOT RAW, NOT HASHED.
  --
  -- A hash is still re-identifiable by anyone who can guess the salt and the
  -- input space, and the input space of one society's residents is small. So
  -- the address is used to derive the two columns below and is never written
  -- down. Everything here is coarse on purpose: "iPhone", not a full user
  -- agent string, which is a fingerprint.
  device text,
  browser text,

  -- From Vercel's own geo headers. Absent in local development, which is
  -- fine - both are nullable and the panel prints an em dash.
  country text,
  city text
);

-- Both the live count and the history list read by event, newest first.
create index if not exists event_visits_event_seen_idx
  on public.event_visits (event_id, last_seen_at desc);

alter table public.event_visits enable row level security;

-- Same reasoning as every table since 009, repeated so it is not lost: this
-- app authenticates through Firebase, not Supabase Auth, so the browser's
-- Supabase client never holds a session and auth.uid() never resolves for it.
-- A policy written against it would be dead code. RLS is therefore enabled
-- with zero policies and every read and write goes through
-- /api/event-access?resource=traffic, which uses the service-role client and
-- checks the Firebase identity server-side.
--
-- Do not add anon/authenticated policies here expecting a direct browser
-- supabase.from("event_visits") call to work. This table is more sensitive
-- than most, not less: it is the one place that says who was reading what.

-- Retention is ninety days, enforced in api/_lib/traffic.ts on the admin's
-- own read rather than by a scheduled job, because this project has no cron
-- and adding one for a single delete is not worth a new moving part. Old
-- browsing records should not accumulate indefinitely, and the table should
-- not grow without limit; one bounded delete on a rare, already-authorised
-- request buys both.
